PATCH http://localhost:3000/users/6a68bfad0a28f77a58aabee4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjhiZmFkMGEyOGY3N2E1OGFhYmVlNCIsImlhdCI6MTc4NTcwNzAxNCwiZXhwIjoxNzg2MzExODE0fQ.NmMFEHjGaw48eXWQiw6qygRdvf5HuxRbrY2_wcOZ0N0

{
    "name": "Artem Aleksandrenko",
    "password": "klrcymsv",
    "role": "admin"
}