const actionTypes = {
    "GENERATE_VALID_MOVES": "GENERATE_VALID_MOVES",
    "CLEAR_VALID_MOVES": "CLEAR_VALID_MOVES",
    "NEW_MOVE": "NEW_MOVE",
    "RESET_GAME": "RESET_GAME",
    "PROMOTION_OPEN": "PROMOTION_OPEN",
    "PROMOTION_CLOSE": "PROMOTION_CLOSE",
    "PROMOTION_MOVE": "PROMOTION_MOVE",
    "SET_POSITION": "SET_POSITION",
    "TOGGLE_ORIENTATION": "TOGGLE_ORIENTATION",
    "SET_ORIENTATION": "SET_ORIENTATION",
    "SET_STATUS": "SET_STATUS",
    "START_TIMER": "START_TIMER",
    "STOP_TIMER": "STOP_TIMER",
    "UPDATE_TIME": "UPDATE_TIME",
    "TIME_UP": "TIME_UP",
    "SET_ROOM_NAME": "SET_ROOM_NAME",
    "SET_BOARD_SIZE": "SET_BOARD_SIZE",
    "SET_MULTIPLAYER": "SET_MULTIPLAYER",
    "SET_VS_BOT": "SET_VS_BOT",
    "SET_OPPONENT": "SET_OPPONENT",
};

export default actionTypes;