const actionTypes = {
    "GENERATE_VALID_MOVES" : "GENERATE_VALID_MOVES",
    "CLEAR_VALID_MOVES" : "CLEAR_VALID_MOVES",
    "NEW_MOVE": "NEW_MOVE",
    "RESET_GAME": "RESET_GAME",
    "PROMOTION_OPEN": "PROMOTION_OPEN",
    "PROMOTION_CLOSE": "PROMOTION_CLOSE",
    "PROMOTION_MOVE": "PROMOTION_MOVE",
    "SET_POSITION": 'SET_POSITION',
    "TOGGLE_ORIENTATION": 'TOGGLE_ORIENTATION',
};

export default actionTypes;